# Generated by Django 5.1.7 on 2025-04-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    models.IntegerField(
                        help_text="지급/차감 포인트", verbose_name="포인트"
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "출석 체크"), (2, "동전 뒤집기")],
                        verbose_name="사유",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_points",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 포인트",
                "verbose_name_plural": "게임 포인트",
                "db_table": "game_point",
            },
        ),
        migrations.CreateModel(
            name="AttendanceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_date",
                    models.DateField(db_index=True, verbose_name="참여 일자"),
                ),
                (
                    "consecutive_days",
                    models.PositiveIntegerField(default=0, verbose_name="연속 일수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "출석 체크 이력",
                "verbose_name_plural": "출석 체크 이력",
                "db_table": "attendance_check",
                "unique_together": {("user", "check_in_date")},
            },
        ),
    ]
