# Generated by Django 5.1.7 on 2025-04-08 05:57

import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="제목", max_length=255, verbose_name="제목"
                    ),
                ),
                ("content", models.TextField(help_text="내용", verbose_name="내용")),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="이벤트 시작 일시", verbose_name="시작 일시"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="이벤트 종료 일시",
                        null=True,
                        verbose_name="종료 일시",
                    ),
                ),
                (
                    "event_start_at",
                    models.DateTimeField(
                        help_text="이벤트 시작 일시", verbose_name="이벤트 시작 일시"
                    ),
                ),
                (
                    "event_end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="이벤트 종료 일시",
                        null=True,
                        verbose_name="이벤트 종료 일시",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="발행 여부"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="이벤트 발행 일시",
                        verbose_name="발행 일시",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "이벤트",
                "verbose_name_plural": "이벤트",
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="제목", max_length=255, verbose_name="제목"
                    ),
                ),
                ("content", models.TextField(help_text="내용", verbose_name="내용")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="발행 여부"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="FAQ 발행 일시",
                        verbose_name="발행 일시",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "db_table": "faq",
            },
        ),
        migrations.CreateModel(
            name="FaqCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="카테고리 이름",
                        max_length=255,
                        verbose_name="카테고리 이름",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "FAQ 카테고리",
                "verbose_name_plural": "FAQ 카테고리",
                "db_table": "faq_category",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="제목", max_length=255, verbose_name="제목"
                    ),
                ),
                ("content", models.TextField(help_text="내용", verbose_name="내용")),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="공지 발행 일시",
                        verbose_name="발행 일시",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="공지 시작 일시", verbose_name="시작 일시"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="공지 종료 일시",
                        null=True,
                        verbose_name="종료 일시",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="발행 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
                "db_table": "notice",
            },
        ),
    ]
