# Generated by Django 5.1.7 on 2025-04-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                help_text="이벤트 작성자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="author",
            field=models.ForeignKey(
                help_text="FAQ 작성자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                help_text="FAQ 카테고리",
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.faqcategory",
                verbose_name="카테고리",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="author",
            field=models.ForeignKey(
                help_text="공지 작성자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
