# Generated by Django 5.1.7 on 2025-04-08 05:57

import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="이미지"),
                ),
                (
                    "comments_count",
                    models.IntegerField(default=0, verbose_name="댓글 수"),
                ),
                (
                    "likes_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "reported_count",
                    models.IntegerField(default=0, verbose_name="신고된 수"),
                ),
                ("published_at", models.DateTimeField(verbose_name="발행 일시")),
                (
                    "is_displayed",
                    models.BooleanField(default=True, verbose_name="노출 여부"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "피드",
                "verbose_name_plural": "피드",
                "db_table": "feed",
            },
        ),
        migrations.CreateModel(
            name="FeedComment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "likes_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "reported_count",
                    models.IntegerField(default=0, verbose_name="신고 수"),
                ),
                ("reply_count", models.IntegerField(default=0, verbose_name="답글 수")),
                (
                    "is_displayed",
                    models.BooleanField(default=True, verbose_name="노출 여부"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "피드 댓글",
                "verbose_name_plural": "피드 댓글",
                "db_table": "feed_comment",
            },
        ),
        migrations.CreateModel(
            name="FeedCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "피드 댓글 좋아요",
                "verbose_name_plural": "피드 댓글 좋아요",
                "db_table": "feed_comment_like",
            },
        ),
        migrations.CreateModel(
            name="FeedCommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_reason",
                    models.IntegerField(
                        choices=[
                            (1, "부적절한 내용"),
                            (2, "스팸"),
                            (3, "혐오 발언"),
                            (4, "기타"),
                        ],
                        verbose_name="신고 유형",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="내용"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "피드 댓글 신고",
                "verbose_name_plural": "피드 댓글 신고",
                "db_table": "feed_comment_report",
            },
        ),
        migrations.CreateModel(
            name="FeedLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "피드 좋아요",
                "verbose_name_plural": "피드 좋아요",
                "db_table": "feed_like",
            },
        ),
        migrations.CreateModel(
            name="FeedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_reason",
                    models.IntegerField(
                        choices=[
                            (1, "부적절한 내용"),
                            (2, "스팸"),
                            (3, "혐오 발언"),
                            (4, "기타"),
                        ],
                        verbose_name="신고 유형",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="내용"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "피드 신고",
                "verbose_name_plural": "피드 신고",
                "db_table": "feed_report",
            },
        ),
        migrations.CreateModel(
            name="FeedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="태그명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "피드 태그",
                "verbose_name_plural": "피드 태그",
                "db_table": "feed_tag",
            },
        ),
    ]
