# Generated by Django 5.1.7 on 2025-04-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="feedcomment",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_comments",
                to="feed.feed",
                verbose_name="피드",
            ),
        ),
        migrations.AddField(
            model_name="feedcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="feed.feedcomment",
                verbose_name="부모 댓글",
            ),
        ),
        migrations.AddField(
            model_name="feedcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="feedcommentlike",
            name="feed_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_comment_likes",
                to="feed.feedcomment",
                verbose_name="피드 댓글",
            ),
        ),
        migrations.AddField(
            model_name="feedcommentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_comment_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="feedcommentreport",
            name="feed_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_comment_reports",
                to="feed.feedcomment",
                verbose_name="피드 댓글",
            ),
        ),
        migrations.AddField(
            model_name="feedcommentreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_comment_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="feedlike",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_likes",
                to="feed.feed",
                verbose_name="피드",
            ),
        ),
        migrations.AddField(
            model_name="feedlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="feedreport",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_reports",
                to="feed.feed",
                verbose_name="피드",
            ),
        ),
        migrations.AddField(
            model_name="feedreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="tags",
            field=models.ManyToManyField(
                related_name="feeds", to="feed.feedtag", verbose_name="태그"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedcommentlike",
            unique_together={("user", "feed_comment")},
        ),
        migrations.AlterUniqueTogether(
            name="feedcommentreport",
            unique_together={("user", "feed_comment")},
        ),
        migrations.AlterUniqueTogether(
            name="feedlike",
            unique_together={("user", "feed")},
        ),
        migrations.AlterUniqueTogether(
            name="feedreport",
            unique_together={("user", "feed")},
        ),
    ]
