# Generated by Django 5.1.7 on 2025-04-09 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAgreementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="변경 전 사용자 약관 동의 정보(변경 일시, 동의 여부, 약관 정보 등)",
                        verbose_name="변경 전 사용자 약관 동의 정보",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
            ],
            options={
                "verbose_name": "사용자 약관 동의 이력",
                "verbose_name_plural": "사용자 약관 동의 이력",
                "db_table": "user_agreement_history",
            },
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="약관 제목")),
                ("content", models.TextField(verbose_name="약관 내용")),
                ("version", models.CharField(max_length=20, verbose_name="약관 버전")),
                (
                    "agreement_type",
                    models.IntegerField(
                        choices=[
                            (1, "서비스 약관"),
                            (2, "개인정보 처리 방침"),
                            (3, "마케팅 약관"),
                        ],
                        help_text="1: 서비스 약관, 2: 개인정보 처리 방침, 3: 마케팅 약관",
                        verbose_name="약관 타입",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="약관 목록에서 표시되는 순서입니다.",
                        verbose_name="약관 순서",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="사용자가 동의해야 하는 필수 약관인지 여부를 나타냅니다.",
                        verbose_name="필수 동의 여부",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="이 약관 개정 전의 이전 버전 약관을 참조합니다.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="agreement.agreement",
                        verbose_name="이전 버전",
                    ),
                ),
            ],
            options={
                "verbose_name": "약관 정보",
                "verbose_name_plural": "약관 정보",
                "db_table": "agreement",
            },
        ),
        migrations.CreateModel(
            name="UserAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_agreed",
                    models.BooleanField(default=False, verbose_name="동의 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_agreements",
                        to="agreement.agreement",
                        verbose_name="약관",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 약관 동의 정보",
                "verbose_name_plural": "사용자 약관 동의 정보",
                "db_table": "user_agreement",
            },
        ),
    ]
