# Generated by Django 5.1.7 on 2025-04-09 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agreement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useragreement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_agreements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="useragreementhistory",
            name="user_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="agreement.useragreement",
                verbose_name="사용자 약관 동의 정보",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useragreement",
            unique_together={("user", "agreement")},
        ),
    ]
