# Generated by Django 5.0.6 on 2024-07-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("to_set", models.JSONField(default=list, verbose_name="수신자")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "대기"), ("S", "성공"), ("F", "실패")],
                        default="R",
                        max_length=1,
                        verbose_name="상태",
                    ),
                ),
                (
                    "fail_reason",
                    models.TextField(blank=True, default="", verbose_name="실패사유"),
                ),
            ],
            options={
                "verbose_name": "이메일 로그",
                "verbose_name_plural": "이메일 로그",
                "db_table": "email_log",
            },
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("to_set", models.JSONField(default=list, verbose_name="수신자")),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "대기"), ("S", "성공"), ("F", "실패")],
                        default="R",
                        max_length=1,
                        verbose_name="상태",
                    ),
                ),
                (
                    "fail_reason",
                    models.TextField(blank=True, default="", verbose_name="실패사유"),
                ),
            ],
            options={
                "verbose_name": "문자 로그",
                "verbose_name_plural": "문자 로그",
                "db_table": "sms_log",
            },
        ),
        migrations.CreateModel(
            name="PushLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "대기"), ("S", "성공"), ("F", "실패")],
                        default="R",
                        max_length=1,
                        verbose_name="상태",
                    ),
                ),
                (
                    "fail_reason",
                    models.TextField(blank=True, default="", verbose_name="실패사유"),
                ),
                (
                    "to_set",
                    models.ManyToManyField(to="device.device", verbose_name="수신자"),
                ),
            ],
            options={
                "verbose_name": "푸시 로그",
                "verbose_name_plural": "푸시 로그",
                "db_table": "push_log",
            },
        ),
    ]
