# Generated by Django 5.0.6 on 2024-07-20 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="파일 ID"
                    ),
                ),
                ("file_name", models.CharField(max_length=100, verbose_name="파일명")),
                ("file_size", models.IntegerField(default=0, verbose_name="파일 크기")),
                (
                    "object_key",
                    models.CharField(max_length=255, verbose_name="파일 URL"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "대기"), (1, "완료"), (2, "실패"), (3, "삭제")],
                        default=0,
                        verbose_name="파일 상태",
                    ),
                ),
                (
                    "content_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="컨텐츠 레이블",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "파일",
                "verbose_name_plural": "파일",
                "db_table": "file",
            },
        ),
    ]
