# Generated by Django 5.1.7 on 2025-04-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True, verbose_name="UUID")),
                (
                    "platform",
                    models.CharField(
                        choices=[(1, "Android"), (2, "iOS"), (3, "Web")],
                        default=3,
                        max_length=50,
                        verbose_name="플랫폼",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "디바이스",
                "verbose_name_plural": "디바이스",
                "db_table": "device",
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, verbose_name="토큰")),
                (
                    "endpoint_arn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="엔드포인트 ARN",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="유효 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to="device.device",
                        verbose_name="디바이스",
                    ),
                ),
            ],
            options={
                "verbose_name": "푸시 토큰",
                "verbose_name_plural": "푸시 토큰",
                "db_table": "push_token",
                "unique_together": {("device", "token")},
            },
        ),
    ]
