# Generated by Django 5.1.7 on 2025-04-08 05:57

import django.db.models.deletion
import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="다운로드 사유",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "파일 다운로드 이력",
                "verbose_name_plural": "파일 다운로드 이력",
                "db_table": "file_download_history",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="저장에 사용되는 파일 ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=100, verbose_name="실제 파일명"),
                ),
                (
                    "extension",
                    models.CharField(max_length=10, verbose_name="파일 확장자"),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="파일 크기")),
                (
                    "object_key",
                    models.TextField(blank=True, null=True, verbose_name="파일 URL"),
                ),
                (
                    "object_id",
                    models.CharField(
                        max_length=36, null=True, verbose_name="컨텐츠 ID"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "준비"),
                            (2, "생성 완료"),
                            (3, "업로드 성공"),
                            (4, "업로드 실패"),
                            (5, "삭제"),
                        ],
                        default=1,
                        verbose_name="파일 상태",
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="만료일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="contenttypes.contenttype",
                        verbose_name="컨텐츠 타입",
                    ),
                ),
            ],
            options={
                "verbose_name": "파일",
                "verbose_name_plural": "파일",
                "db_table": "file",
            },
        ),
    ]
